# Dockerfile.template for balena managed TAKNUC Containers
# - See Dockerfile for non-balena TAKNUCContainers
#
# Author: Greg Albrecht W2GMD <oss@undef.net>
# Copyright: Copyright 2021 Orion Labs, Inc.
# License: Apache License, Version 2.0
# Source: https://github.com/ampledata/TAKNUC
#

FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.8-buster-build

RUN install_packages libxml2-dev libxslt-dev libcairo2-dev vim

RUN pip3 install FreeTAKServer[ui] requests

WORKDIR /freetakserver

# Startup:
COPY docker-entrypoint.sh .
COPY run_app.sh .
COPY MainConfig.py /usr/local/lib/python3.8/site-packages/FreeTAKServer/controllers/configuration/MainConfig.py

ENV FTS_DB_PATH /persist-data/freetakserver/FTSDataBase.db
ENV FTS_CERTS_PATH /persist-data/freetakserver/certs
ENV FTS_CLIENT_CERTS_PATH /persist-data/freetakserver/certs/ClientPackages
ENV ExCheckMainPath /persist-data/freetakserver/ExCheck
ENV ExCheckFilePath /persist-data/freetakserver/ExCheck/template
ENV ExCheckChecklistFilePath /persist-data/freetakserver/ExCheck/checklist
ENV DataPackageFilePath /persist-data/freetakserver/FreeTAKServerDataPackageFolder

ENTRYPOINT ["/freetakserver/docker-entrypoint.sh"]

CMD ["/freetakserver/run_app.sh"]
